[package]
name = "dfly-cluster"
version.workspace = true
edition.workspace = true

[dependencies]
dfly-common = { path = "../dfly-common" }

[dev-dependencies]
googletest = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
